import os
import shutil
import argparse
from pathlib import Path

# Path configuration
LIBRARY_DIR = Path(".github/skills/.library")
SKILLS_DIR = Path(".github/skills")
INSTRUCTIONS_DIR = Path(".github/instructions")

# Stack definitions are intentionally empty in the open-source release.
# Users define their own stacks via /copilot-init which generates
# instructions and skills dynamically based on project analysis.
STACKS = {}

def update_manifest_profile(profile):
    manifest_path = Path(".github/.copilot-dev.tson")
    if manifest_path.exists():
        import json
        try:
            with open(manifest_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data["project_profile"] = profile
            from tson_utils import to_tson
            with open(manifest_path, "w", encoding="utf-8") as f:
                f.write(to_tson(data))
            print(f"  📝 Profile '{profile}' saved to manifest.")
        except Exception as e:
            print(f"  ⚠️ Could not update manifest: {e}")

def setup_stack(stack_name):
    config = STACKS.get(stack_name, {
        "skills": [],
        "instructions": [],
        "folders": ["src", "tests", "docs/adr"]
    })
    
    if stack_name not in STACKS:
        print(f"⚠️ Stack '{stack_name}' is not predefined. Using generic structure...")
    else:
        print(f"🚀 Initializing Blueprint for: {stack_name}...")

    # 1. Update the profile in the manifest
    update_manifest_profile(config.get("profile", ""))

    # 2. Activate Skills from the library
    for skill in config.get("skills", []):
        src = LIBRARY_DIR / skill
        dst = SKILLS_DIR / skill
        if src.exists():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
            print(f"  ✅ Skill activated: {skill}")

    # 3. Ensure base directories exist
    for folder in config.get("folders", []):
        Path(folder).mkdir(parents=True, exist_ok=True)
        print(f"  📁 Directory created: {folder}")

    # 4. Create initial state file
    memory_dir = Path(".github/memory")
    memory_dir.mkdir(parents=True, exist_ok=True)
    state_file = memory_dir / "active_state.tson"
    
    if not state_file.exists():
        with open(state_file, "w", encoding="utf-8") as f:
            f.write(f'# Initial state generated by Blueprint\n{{\n  "objective": "Initialize {stack_name} project",\n  "status": "ready",\n  "current_agent": "dispatcher",\n  "pending_tasks": ["Create project structure", "Define architecture"]\n}}')
        print(f"  🧠 Memory initialized at {state_file}")

    print(f"\n✨ Blueprint '{stack_name}' applied successfully.")
    print("👉 Run 'bash .github/hooks/scripts/sync_agents.sh' to finalize the setup.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Swagentics Project Blueprint")
    parser.add_argument("--stack", required=True, help="Project stack to initialize")
    args = parser.parse_args()
    setup_stack(args.stack)
